device_id = "6a5c65c5-fe36-47e9-86e9-bee69679adab"
access_token = "694071e7-9f58-4cf2-a890-fe1b83bfc054"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8c83:d1bf:437b:ae78:9da1"
wg_private_key = "KPdpudWp7rlzUEUpYUQzjmUNoAkg1s4hl6gGuhGgr0Y="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "iQwA"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.5"
