device_id = "010cb054-fcfa-4398-8793-eba422c89d46"
access_token = "616a9f3c-23ad-485b-9909-aac42582252a"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8d2c:893f:cbed:1cd4:e9ed"
wg_private_key = "8DMcDtdmpixc8eYh7B6cYHzPUvVrzdg6Sqn6ab8xvWg="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "lmVA"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.10"
