device_id = "d124efcd-b15d-4dda-a6d7-18a78f7b5fa9"
access_token = "21ce5da1-ab76-480a-ad84-592526fd30be"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8314:cecd:92a:77e8:5020"
wg_private_key = "yL1uRLzG9Cte2odkOUpcsbZeL/bg/2mH5Y//Uo3KFlY="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "QE0g"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.5"
