device_id = "2233e30b-5e74-41ed-a2d1-7b4570307769"
access_token = "f245dcc3-b0a3-4729-ad84-d63e56bb2e78"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:86eb:fe41:7b35:49b8:a94d"
wg_private_key = "4MXDJbHwDm0lfKwGdhscauauVilKWxP6ImOQDh/fdFA="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "r33Q"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "104.16.24.84"
