device_id = "97195524-a43d-41d1-a225-8bc86f4dc5bb"
access_token = "53d9da85-81e6-4f32-9ba2-f7c3f1199932"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8da1:70d3:9bf6:7de:72ab"
wg_private_key = "yO4/J1ODnQgBnFU8c7tBwgI7nHhXqGYGq3TdO/6NrWI="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "9zwF"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
