device_id = "00e0997c-5bc3-4fe9-9b84-7f744da5667c"
access_token = "2ff9ec7d-1da5-4df0-8e3e-0cbbeefe3252"
cert_pem = """
-----BEGIN CERTIFICATE-----
MIHsMIGToAMCAQICAQAwCgYIKoZIzj0EAwIwADAeFw0yNjA5MjgxMTAwMzVaFw0y
NzA5MjgxMTAwMzVaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQM0OKZI/ZI
BsecdFhcPCSTCJq2JvpEwncRlvZhq/jNqrFAmj/VkdQQj88Agixr/mi6dm8Hq2Zs
qK7Be0UCcs61MAoGCCqGSM49BAMCA0gAMEUCIQCJOREHaX6QeadA5i88Z9RC5AFT
NxvkHkv66eBNERAkigIgQzadUz4WXDJzDGXAHBjd/4zuQpK+vd4OP51FebH6TZw=
-----END CERTIFICATE-----
"""
key_pem = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgczRMdg2oH5aND4FK
lNW4ktthfLhXKKtJo4O7H20r0/WhRANCAAQM0OKZI/ZIBsecdFhcPCSTCJq2JvpE
wncRlvZhq/jNqrFAmj/VkdQQj88Agixr/mi6dm8Hq2ZsqK7Be0UCcs61
-----END PRIVATE KEY-----
"""
cert_issued_at = 1790593239
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:87ed:7d4d:f4ea:a191:4fb9"
wg_private_key = "2MsjtAhzgHrn1ML8S4BRI4qbhV5FNd9r58aMxDKjpHw="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "D6IW"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.10"
