device_id = "e802fe06-3b90-4db6-9610-e4a6da072cf3"
access_token = "05a28e3c-a9fd-4473-9ba3-686e9a03dbd3"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8383:4289:af0b:8664:4abc"
wg_private_key = "MGe2yVsg0mI+s1pLEgK3dmkjjhxg1q1qVt+Pe0BO63U="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "TvCB"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.7"
