device_id = "db3e36af-b561-493c-9da3-2d5cdb8be8a4"
access_token = "7c7f7c37-33fe-4820-a755-603572f27fec"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:81c1:d93c:694a:a560:34df"
wg_private_key = "uMrPa2SaaV4TvWxpWKUg33FEQ9rg+10H+5oxYQu9s0U="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "LCoW"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.2"
