// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'smart_core_types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BehaviorAnalysisReport dco_decode_behavior_analysis_report(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  GamingBoostConfig dco_decode_box_autoadd_gaming_boost_config(dynamic raw);

  @protected
  ProxyNode dco_decode_box_autoadd_proxy_node(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  VerifiedDns dco_decode_box_autoadd_verified_dns(dynamic raw);

  @protected
  CalibratedConnectionProfile dco_decode_calibrated_connection_profile(
    dynamic raw,
  );

  @protected
  ConnectionQualityMetrics dco_decode_connection_quality_metrics(dynamic raw);

  @protected
  DeviationSeverity dco_decode_deviation_severity(dynamic raw);

  @protected
  DnsScannerProgress dco_decode_dns_scanner_progress(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GamingBenchmarkResult dco_decode_gaming_benchmark_result(dynamic raw);

  @protected
  GamingBoostConfig dco_decode_gaming_boost_config(dynamic raw);

  @protected
  GamingDnsReport dco_decode_gaming_dns_report(dynamic raw);

  @protected
  GamingLiveMetrics dco_decode_gaming_live_metrics(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<GamingDnsReport> dco_decode_list_gaming_dns_report(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProxyNode> dco_decode_list_proxy_node(dynamic raw);

  @protected
  List<ScannedDnsResult> dco_decode_list_scanned_dns_result(dynamic raw);

  @protected
  List<VerifiedDns> dco_decode_list_verified_dns(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  VerifiedDns? dco_decode_opt_box_autoadd_verified_dns(dynamic raw);

  @protected
  ProxyNode dco_decode_proxy_node(dynamic raw);

  @protected
  ScannedDnsResult dco_decode_scanned_dns_result(dynamic raw);

  @protected
  ScannerStats dco_decode_scanner_stats(dynamic raw);

  @protected
  SlipNetProfile dco_decode_slip_net_profile(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VerifiedDns dco_decode_verified_dns(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BehaviorAnalysisReport sse_decode_behavior_analysis_report(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  GamingBoostConfig sse_decode_box_autoadd_gaming_boost_config(
    SseDeserializer deserializer,
  );

  @protected
  ProxyNode sse_decode_box_autoadd_proxy_node(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VerifiedDns sse_decode_box_autoadd_verified_dns(SseDeserializer deserializer);

  @protected
  CalibratedConnectionProfile sse_decode_calibrated_connection_profile(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionQualityMetrics sse_decode_connection_quality_metrics(
    SseDeserializer deserializer,
  );

  @protected
  DeviationSeverity sse_decode_deviation_severity(SseDeserializer deserializer);

  @protected
  DnsScannerProgress sse_decode_dns_scanner_progress(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GamingBenchmarkResult sse_decode_gaming_benchmark_result(
    SseDeserializer deserializer,
  );

  @protected
  GamingBoostConfig sse_decode_gaming_boost_config(
    SseDeserializer deserializer,
  );

  @protected
  GamingDnsReport sse_decode_gaming_dns_report(SseDeserializer deserializer);

  @protected
  GamingLiveMetrics sse_decode_gaming_live_metrics(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<GamingDnsReport> sse_decode_list_gaming_dns_report(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProxyNode> sse_decode_list_proxy_node(SseDeserializer deserializer);

  @protected
  List<ScannedDnsResult> sse_decode_list_scanned_dns_result(
    SseDeserializer deserializer,
  );

  @protected
  List<VerifiedDns> sse_decode_list_verified_dns(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VerifiedDns? sse_decode_opt_box_autoadd_verified_dns(
    SseDeserializer deserializer,
  );

  @protected
  ProxyNode sse_decode_proxy_node(SseDeserializer deserializer);

  @protected
  ScannedDnsResult sse_decode_scanned_dns_result(SseDeserializer deserializer);

  @protected
  ScannerStats sse_decode_scanner_stats(SseDeserializer deserializer);

  @protected
  SlipNetProfile sse_decode_slip_net_profile(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VerifiedDns sse_decode_verified_dns(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_behavior_analysis_report(
    BehaviorAnalysisReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gaming_boost_config(
    GamingBoostConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proxy_node(
    ProxyNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_verified_dns(
    VerifiedDns self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calibrated_connection_profile(
    CalibratedConnectionProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_quality_metrics(
    ConnectionQualityMetrics self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_deviation_severity(
    DeviationSeverity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dns_scanner_progress(
    DnsScannerProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_gaming_benchmark_result(
    GamingBenchmarkResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaming_boost_config(
    GamingBoostConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaming_dns_report(
    GamingDnsReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaming_live_metrics(
    GamingLiveMetrics self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gaming_dns_report(
    List<GamingDnsReport> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_node(
    List<ProxyNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scanned_dns_result(
    List<ScannedDnsResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_verified_dns(
    List<VerifiedDns> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_verified_dns(
    VerifiedDns? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_node(ProxyNode self, SseSerializer serializer);

  @protected
  void sse_encode_scanned_dns_result(
    ScannedDnsResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scanner_stats(ScannerStats self, SseSerializer serializer);

  @protected
  void sse_encode_slip_net_profile(
    SlipNetProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_verified_dns(VerifiedDns self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
