// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1904304848;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_client',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiSimpleGetAetherBootstrapProgress();

  Future<String> crateApiSimpleGetAetherStatusText();

  Future<String> crateApiSimpleGetPsiphonStatusText();

  Future<ScannerStats> crateApiSimpleGetScannerStats();

  Future<int> crateApiSimpleGetTorBootstrapProgress();

  Future<List<VerifiedDns>> crateApiSimpleGetVaultDnsList();

  Future<bool> crateApiSimpleIsAetherBootstrapDone();

  Future<bool> crateApiSimpleIsAetherConnected();

  Future<bool> crateApiSimpleIsConnected();

  Future<bool> crateApiSimpleIsDnsActive();

  Future<bool> crateApiSimpleIsHybridConnected();

  Future<bool> crateApiSimpleIsPsiphonBootstrapDone();

  Future<bool> crateApiSimpleIsPsiphonConnected();

  Future<bool> crateApiSimpleIsPsiphonMasqueConnected();

  Future<bool> crateApiSimpleIsTorConnected();

  Future<bool> crateApiSimpleIsTorMasqueConnected();

  Future<List<ProxyNode>> crateApiSimpleParseImportLinks({
    required String input,
  });

  Future<int> crateApiSimplePingDnsServer({required String ip});

  Future<int> crateApiSimplePingProxyServer({
    required String host,
    required int port,
  });

  Future<String> crateApiSimpleResetSystemDns();

  Future<List<ProxyNode>> crateApiSimpleRunCloudflareScanner({
    required String uuid,
    required String path,
    required String worker,
    required String scanMode,
    required bool earlyStop,
  });

  Future<List<VerifiedDns>> crateApiSimpleRunDnsRescueScan({
    String? customDnsList,
  });

  Future<String> crateApiSimpleSetSystemDns({
    required String primary,
    required String secondary,
  });

  Future<String> crateApiSimpleStartAetherCore({
    required String binaryPath,
    required String mode,
    required String noize,
    String? warpKey,
    String? team,
    required bool useSystemProxy,
  });

  Future<String> crateApiSimpleStartHybridConnection({
    required String singboxPath,
    required String aetherPath,
    required ProxyNode selectedNode,
    required String aetherMode,
    required String aetherNoize,
    String? aetherWarpKey,
    String? aetherTeam,
    required bool useSystemProxy,
    required bool useTunMode,
    required String dnsType,
    required String dnsPrimary,
    required String dnsSecondary,
    String? dnsDotHost,
    String? utlsFingerprint,
  });

  Future<String> crateApiSimpleStartProxyWithNode({
    required String binaryPath,
    required ProxyNode selectedNode,
    required bool useSystemProxy,
    String? customSni,
    required bool enableFragment,
    required bool enableRecordFragment,
    String? tlsSpoof,
    required bool useTunMode,
    required String dnsType,
    required String dnsPrimary,
    required String dnsSecondary,
    String? dnsDohUrl,
    String? dnsDotHost,
    String? utlsFingerprint,
    String? fragmentFallbackDelay,
  });

  Future<String> crateApiSimpleStartPsiphonCore({
    required String binaryPath,
    required String countryCode,
    required bool useSystemProxy,
  });

  Future<String> crateApiSimpleStartPsiphonOverMasque({
    required String psiphonPath,
    required String aetherPath,
    required String countryCode,
    required String aetherMode,
    required String aetherNoize,
    String? aetherWarpKey,
    String? aetherTeam,
    required bool useSystemProxy,
  });

  Future<String> crateApiSimpleStartTorCore({
    required String binaryPath,
    required String countryCode,
    required bool useSystemProxy,
  });

  Future<String> crateApiSimpleStartTorOverMasque({
    required String torPath,
    required String aetherPath,
    required String countryCode,
    required String aetherMode,
    required String aetherNoize,
    String? aetherWarpKey,
    String? aetherTeam,
    required bool useSystemProxy,
  });

  Future<String> crateApiSimpleStopAetherCore();

  Future<void> crateApiSimpleStopCloudflareScanner();

  Future<String> crateApiSimpleStopHybridConnection();

  Future<String> crateApiSimpleStopProxyCore();

  Future<String> crateApiSimpleStopPsiphonCore();

  Future<String> crateApiSimpleStopPsiphonOverMasque();

  Future<String> crateApiSimpleStopTorCore();

  Future<String> crateApiSimpleStopTorOverMasque();

  Future<VerifiedDns?> crateApiSimpleVerifyDnsIp({required String ip});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiSimpleGetAetherBootstrapProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetAetherBootstrapProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetAetherBootstrapProgressConstMeta =>
      const TaskConstMeta(
        debugName: "get_aether_bootstrap_progress",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleGetAetherStatusText() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetAetherStatusTextConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetAetherStatusTextConstMeta =>
      const TaskConstMeta(debugName: "get_aether_status_text", argNames: []);

  @override
  Future<String> crateApiSimpleGetPsiphonStatusText() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetPsiphonStatusTextConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetPsiphonStatusTextConstMeta =>
      const TaskConstMeta(debugName: "get_psiphon_status_text", argNames: []);

  @override
  Future<ScannerStats> crateApiSimpleGetScannerStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scanner_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetScannerStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetScannerStatsConstMeta =>
      const TaskConstMeta(debugName: "get_scanner_stats", argNames: []);

  @override
  Future<int> crateApiSimpleGetTorBootstrapProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTorBootstrapProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTorBootstrapProgressConstMeta =>
      const TaskConstMeta(
        debugName: "get_tor_bootstrap_progress",
        argNames: [],
      );

  @override
  Future<List<VerifiedDns>> crateApiSimpleGetVaultDnsList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_verified_dns,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetVaultDnsListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetVaultDnsListConstMeta =>
      const TaskConstMeta(debugName: "get_vault_dns_list", argNames: []);

  @override
  Future<bool> crateApiSimpleIsAetherBootstrapDone() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsAetherBootstrapDoneConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsAetherBootstrapDoneConstMeta =>
      const TaskConstMeta(debugName: "is_aether_bootstrap_done", argNames: []);

  @override
  Future<bool> crateApiSimpleIsAetherConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsAetherConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsAetherConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_aether_connected", argNames: []);

  @override
  Future<bool> crateApiSimpleIsConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_connected", argNames: []);

  @override
  Future<bool> crateApiSimpleIsDnsActive() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsDnsActiveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsDnsActiveConstMeta =>
      const TaskConstMeta(debugName: "is_dns_active", argNames: []);

  @override
  Future<bool> crateApiSimpleIsHybridConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsHybridConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsHybridConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_hybrid_connected", argNames: []);

  @override
  Future<bool> crateApiSimpleIsPsiphonBootstrapDone() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsPsiphonBootstrapDoneConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsPsiphonBootstrapDoneConstMeta =>
      const TaskConstMeta(debugName: "is_psiphon_bootstrap_done", argNames: []);

  @override
  Future<bool> crateApiSimpleIsPsiphonConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsPsiphonConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsPsiphonConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_psiphon_connected", argNames: []);

  @override
  Future<bool> crateApiSimpleIsPsiphonMasqueConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsPsiphonMasqueConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsPsiphonMasqueConnectedConstMeta =>
      const TaskConstMeta(
        debugName: "is_psiphon_masque_connected",
        argNames: [],
      );

  @override
  Future<bool> crateApiSimpleIsTorConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsTorConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsTorConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_tor_connected", argNames: []);

  @override
  Future<bool> crateApiSimpleIsTorMasqueConnected() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsTorMasqueConnectedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsTorMasqueConnectedConstMeta =>
      const TaskConstMeta(debugName: "is_tor_masque_connected", argNames: []);

  @override
  Future<List<ProxyNode>> crateApiSimpleParseImportLinks({
    required String input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_proxy_node,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleParseImportLinksConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleParseImportLinksConstMeta =>
      const TaskConstMeta(debugName: "parse_import_links", argNames: ["input"]);

  @override
  Future<int> crateApiSimplePingDnsServer({required String ip}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ip, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePingDnsServerConstMeta,
        argValues: [ip],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePingDnsServerConstMeta =>
      const TaskConstMeta(debugName: "ping_dns_server", argNames: ["ip"]);

  @override
  Future<int> crateApiSimplePingProxyServer({
    required String host,
    required int port,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePingProxyServerConstMeta,
        argValues: [host, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePingProxyServerConstMeta =>
      const TaskConstMeta(
        debugName: "ping_proxy_server",
        argNames: ["host", "port"],
      );

  @override
  Future<String> crateApiSimpleResetSystemDns() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleResetSystemDnsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleResetSystemDnsConstMeta =>
      const TaskConstMeta(debugName: "reset_system_dns", argNames: []);

  @override
  Future<List<ProxyNode>> crateApiSimpleRunCloudflareScanner({
    required String uuid,
    required String path,
    required String worker,
    required String scanMode,
    required bool earlyStop,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uuid, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(worker, serializer);
          sse_encode_String(scanMode, serializer);
          sse_encode_bool(earlyStop, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_proxy_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRunCloudflareScannerConstMeta,
        argValues: [uuid, path, worker, scanMode, earlyStop],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRunCloudflareScannerConstMeta =>
      const TaskConstMeta(
        debugName: "run_cloudflare_scanner",
        argNames: ["uuid", "path", "worker", "scanMode", "earlyStop"],
      );

  @override
  Future<List<VerifiedDns>> crateApiSimpleRunDnsRescueScan({
    String? customDnsList,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(customDnsList, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_verified_dns,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRunDnsRescueScanConstMeta,
        argValues: [customDnsList],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRunDnsRescueScanConstMeta =>
      const TaskConstMeta(
        debugName: "run_dns_rescue_scan",
        argNames: ["customDnsList"],
      );

  @override
  Future<String> crateApiSimpleSetSystemDns({
    required String primary,
    required String secondary,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(primary, serializer);
          sse_encode_String(secondary, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSetSystemDnsConstMeta,
        argValues: [primary, secondary],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetSystemDnsConstMeta => const TaskConstMeta(
    debugName: "set_system_dns",
    argNames: ["primary", "secondary"],
  );

  @override
  Future<String> crateApiSimpleStartAetherCore({
    required String binaryPath,
    required String mode,
    required String noize,
    String? warpKey,
    String? team,
    required bool useSystemProxy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(mode, serializer);
          sse_encode_String(noize, serializer);
          sse_encode_opt_String(warpKey, serializer);
          sse_encode_opt_String(team, serializer);
          sse_encode_bool(useSystemProxy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartAetherCoreConstMeta,
        argValues: [binaryPath, mode, noize, warpKey, team, useSystemProxy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartAetherCoreConstMeta =>
      const TaskConstMeta(
        debugName: "start_aether_core",
        argNames: [
          "binaryPath",
          "mode",
          "noize",
          "warpKey",
          "team",
          "useSystemProxy",
        ],
      );

  @override
  Future<String> crateApiSimpleStartHybridConnection({
    required String singboxPath,
    required String aetherPath,
    required ProxyNode selectedNode,
    required String aetherMode,
    required String aetherNoize,
    String? aetherWarpKey,
    String? aetherTeam,
    required bool useSystemProxy,
    required bool useTunMode,
    required String dnsType,
    required String dnsPrimary,
    required String dnsSecondary,
    String? dnsDotHost,
    String? utlsFingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(singboxPath, serializer);
          sse_encode_String(aetherPath, serializer);
          sse_encode_box_autoadd_proxy_node(selectedNode, serializer);
          sse_encode_String(aetherMode, serializer);
          sse_encode_String(aetherNoize, serializer);
          sse_encode_opt_String(aetherWarpKey, serializer);
          sse_encode_opt_String(aetherTeam, serializer);
          sse_encode_bool(useSystemProxy, serializer);
          sse_encode_bool(useTunMode, serializer);
          sse_encode_String(dnsType, serializer);
          sse_encode_String(dnsPrimary, serializer);
          sse_encode_String(dnsSecondary, serializer);
          sse_encode_opt_String(dnsDotHost, serializer);
          sse_encode_opt_String(utlsFingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartHybridConnectionConstMeta,
        argValues: [
          singboxPath,
          aetherPath,
          selectedNode,
          aetherMode,
          aetherNoize,
          aetherWarpKey,
          aetherTeam,
          useSystemProxy,
          useTunMode,
          dnsType,
          dnsPrimary,
          dnsSecondary,
          dnsDotHost,
          utlsFingerprint,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartHybridConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "start_hybrid_connection",
        argNames: [
          "singboxPath",
          "aetherPath",
          "selectedNode",
          "aetherMode",
          "aetherNoize",
          "aetherWarpKey",
          "aetherTeam",
          "useSystemProxy",
          "useTunMode",
          "dnsType",
          "dnsPrimary",
          "dnsSecondary",
          "dnsDotHost",
          "utlsFingerprint",
        ],
      );

  @override
  Future<String> crateApiSimpleStartProxyWithNode({
    required String binaryPath,
    required ProxyNode selectedNode,
    required bool useSystemProxy,
    String? customSni,
    required bool enableFragment,
    required bool enableRecordFragment,
    String? tlsSpoof,
    required bool useTunMode,
    required String dnsType,
    required String dnsPrimary,
    required String dnsSecondary,
    String? dnsDohUrl,
    String? dnsDotHost,
    String? utlsFingerprint,
    String? fragmentFallbackDelay,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_box_autoadd_proxy_node(selectedNode, serializer);
          sse_encode_bool(useSystemProxy, serializer);
          sse_encode_opt_String(customSni, serializer);
          sse_encode_bool(enableFragment, serializer);
          sse_encode_bool(enableRecordFragment, serializer);
          sse_encode_opt_String(tlsSpoof, serializer);
          sse_encode_bool(useTunMode, serializer);
          sse_encode_String(dnsType, serializer);
          sse_encode_String(dnsPrimary, serializer);
          sse_encode_String(dnsSecondary, serializer);
          sse_encode_opt_String(dnsDohUrl, serializer);
          sse_encode_opt_String(dnsDotHost, serializer);
          sse_encode_opt_String(utlsFingerprint, serializer);
          sse_encode_opt_String(fragmentFallbackDelay, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartProxyWithNodeConstMeta,
        argValues: [
          binaryPath,
          selectedNode,
          useSystemProxy,
          customSni,
          enableFragment,
          enableRecordFragment,
          tlsSpoof,
          useTunMode,
          dnsType,
          dnsPrimary,
          dnsSecondary,
          dnsDohUrl,
          dnsDotHost,
          utlsFingerprint,
          fragmentFallbackDelay,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartProxyWithNodeConstMeta =>
      const TaskConstMeta(
        debugName: "start_proxy_with_node",
        argNames: [
          "binaryPath",
          "selectedNode",
          "useSystemProxy",
          "customSni",
          "enableFragment",
          "enableRecordFragment",
          "tlsSpoof",
          "useTunMode",
          "dnsType",
          "dnsPrimary",
          "dnsSecondary",
          "dnsDohUrl",
          "dnsDotHost",
          "utlsFingerprint",
          "fragmentFallbackDelay",
        ],
      );

  @override
  Future<String> crateApiSimpleStartPsiphonCore({
    required String binaryPath,
    required String countryCode,
    required bool useSystemProxy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(countryCode, serializer);
          sse_encode_bool(useSystemProxy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartPsiphonCoreConstMeta,
        argValues: [binaryPath, countryCode, useSystemProxy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartPsiphonCoreConstMeta =>
      const TaskConstMeta(
        debugName: "start_psiphon_core",
        argNames: ["binaryPath", "countryCode", "useSystemProxy"],
      );

  @override
  Future<String> crateApiSimpleStartPsiphonOverMasque({
    required String psiphonPath,
    required String aetherPath,
    required String countryCode,
    required String aetherMode,
    required String aetherNoize,
    String? aetherWarpKey,
    String? aetherTeam,
    required bool useSystemProxy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(psiphonPath, serializer);
          sse_encode_String(aetherPath, serializer);
          sse_encode_String(countryCode, serializer);
          sse_encode_String(aetherMode, serializer);
          sse_encode_String(aetherNoize, serializer);
          sse_encode_opt_String(aetherWarpKey, serializer);
          sse_encode_opt_String(aetherTeam, serializer);
          sse_encode_bool(useSystemProxy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartPsiphonOverMasqueConstMeta,
        argValues: [
          psiphonPath,
          aetherPath,
          countryCode,
          aetherMode,
          aetherNoize,
          aetherWarpKey,
          aetherTeam,
          useSystemProxy,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartPsiphonOverMasqueConstMeta =>
      const TaskConstMeta(
        debugName: "start_psiphon_over_masque",
        argNames: [
          "psiphonPath",
          "aetherPath",
          "countryCode",
          "aetherMode",
          "aetherNoize",
          "aetherWarpKey",
          "aetherTeam",
          "useSystemProxy",
        ],
      );

  @override
  Future<String> crateApiSimpleStartTorCore({
    required String binaryPath,
    required String countryCode,
    required bool useSystemProxy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(countryCode, serializer);
          sse_encode_bool(useSystemProxy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartTorCoreConstMeta,
        argValues: [binaryPath, countryCode, useSystemProxy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartTorCoreConstMeta => const TaskConstMeta(
    debugName: "start_tor_core",
    argNames: ["binaryPath", "countryCode", "useSystemProxy"],
  );

  @override
  Future<String> crateApiSimpleStartTorOverMasque({
    required String torPath,
    required String aetherPath,
    required String countryCode,
    required String aetherMode,
    required String aetherNoize,
    String? aetherWarpKey,
    String? aetherTeam,
    required bool useSystemProxy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(torPath, serializer);
          sse_encode_String(aetherPath, serializer);
          sse_encode_String(countryCode, serializer);
          sse_encode_String(aetherMode, serializer);
          sse_encode_String(aetherNoize, serializer);
          sse_encode_opt_String(aetherWarpKey, serializer);
          sse_encode_opt_String(aetherTeam, serializer);
          sse_encode_bool(useSystemProxy, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartTorOverMasqueConstMeta,
        argValues: [
          torPath,
          aetherPath,
          countryCode,
          aetherMode,
          aetherNoize,
          aetherWarpKey,
          aetherTeam,
          useSystemProxy,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartTorOverMasqueConstMeta =>
      const TaskConstMeta(
        debugName: "start_tor_over_masque",
        argNames: [
          "torPath",
          "aetherPath",
          "countryCode",
          "aetherMode",
          "aetherNoize",
          "aetherWarpKey",
          "aetherTeam",
          "useSystemProxy",
        ],
      );

  @override
  Future<String> crateApiSimpleStopAetherCore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStopAetherCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopAetherCoreConstMeta =>
      const TaskConstMeta(debugName: "stop_aether_core", argNames: []);

  @override
  Future<void> crateApiSimpleStopCloudflareScanner() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStopCloudflareScannerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopCloudflareScannerConstMeta =>
      const TaskConstMeta(debugName: "stop_cloudflare_scanner", argNames: []);

  @override
  Future<String> crateApiSimpleStopHybridConnection() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStopHybridConnectionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopHybridConnectionConstMeta =>
      const TaskConstMeta(debugName: "stop_hybrid_connection", argNames: []);

  @override
  Future<String> crateApiSimpleStopProxyCore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStopProxyCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopProxyCoreConstMeta =>
      const TaskConstMeta(debugName: "stop_proxy_core", argNames: []);

  @override
  Future<String> crateApiSimpleStopPsiphonCore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStopPsiphonCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopPsiphonCoreConstMeta =>
      const TaskConstMeta(debugName: "stop_psiphon_core", argNames: []);

  @override
  Future<String> crateApiSimpleStopPsiphonOverMasque() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStopPsiphonOverMasqueConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopPsiphonOverMasqueConstMeta =>
      const TaskConstMeta(debugName: "stop_psiphon_over_masque", argNames: []);

  @override
  Future<String> crateApiSimpleStopTorCore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStopTorCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopTorCoreConstMeta =>
      const TaskConstMeta(debugName: "stop_tor_core", argNames: []);

  @override
  Future<String> crateApiSimpleStopTorOverMasque() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStopTorOverMasqueConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopTorOverMasqueConstMeta =>
      const TaskConstMeta(debugName: "stop_tor_over_masque", argNames: []);

  @override
  Future<VerifiedDns?> crateApiSimpleVerifyDnsIp({required String ip}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ip, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_verified_dns,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleVerifyDnsIpConstMeta,
        argValues: [ip],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleVerifyDnsIpConstMeta =>
      const TaskConstMeta(debugName: "verify_dns_ip", argNames: ["ip"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ProxyNode dco_decode_box_autoadd_proxy_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_proxy_node(raw);
  }

  @protected
  VerifiedDns dco_decode_box_autoadd_verified_dns(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_verified_dns(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProxyNode> dco_decode_list_proxy_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_proxy_node).toList();
  }

  @protected
  List<VerifiedDns> dco_decode_list_verified_dns(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_verified_dns).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  VerifiedDns? dco_decode_opt_box_autoadd_verified_dns(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_verified_dns(raw);
  }

  @protected
  ProxyNode dco_decode_proxy_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProxyNode(
      name: dco_decode_String(arr[0]),
      protocol: dco_decode_String(arr[1]),
      rawUrl: dco_decode_String(arr[2]),
    );
  }

  @protected
  ScannerStats dco_decode_scanner_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ScannerStats(
      totalScanned: dco_decode_i_32(arr[0]),
      aliveCount: dco_decode_i_32(arr[1]),
      deadCount: dco_decode_i_32(arr[2]),
      isRunning: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VerifiedDns dco_decode_verified_dns(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VerifiedDns(
      ip: dco_decode_String(arr[0]),
      latencyMs: dco_decode_i_32(arr[1]),
      worksSingbox: dco_decode_bool(arr[2]),
      worksTor: dco_decode_bool(arr[3]),
      worksPsiphon: dco_decode_bool(arr[4]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ProxyNode sse_decode_box_autoadd_proxy_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_proxy_node(deserializer));
  }

  @protected
  VerifiedDns sse_decode_box_autoadd_verified_dns(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_verified_dns(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProxyNode> sse_decode_list_proxy_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProxyNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_proxy_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<VerifiedDns> sse_decode_list_verified_dns(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VerifiedDns>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_verified_dns(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VerifiedDns? sse_decode_opt_box_autoadd_verified_dns(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_verified_dns(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProxyNode sse_decode_proxy_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_rawUrl = sse_decode_String(deserializer);
    return ProxyNode(
      name: var_name,
      protocol: var_protocol,
      rawUrl: var_rawUrl,
    );
  }

  @protected
  ScannerStats sse_decode_scanner_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalScanned = sse_decode_i_32(deserializer);
    var var_aliveCount = sse_decode_i_32(deserializer);
    var var_deadCount = sse_decode_i_32(deserializer);
    var var_isRunning = sse_decode_bool(deserializer);
    return ScannerStats(
      totalScanned: var_totalScanned,
      aliveCount: var_aliveCount,
      deadCount: var_deadCount,
      isRunning: var_isRunning,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VerifiedDns sse_decode_verified_dns(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ip = sse_decode_String(deserializer);
    var var_latencyMs = sse_decode_i_32(deserializer);
    var var_worksSingbox = sse_decode_bool(deserializer);
    var var_worksTor = sse_decode_bool(deserializer);
    var var_worksPsiphon = sse_decode_bool(deserializer);
    return VerifiedDns(
      ip: var_ip,
      latencyMs: var_latencyMs,
      worksSingbox: var_worksSingbox,
      worksTor: var_worksTor,
      worksPsiphon: var_worksPsiphon,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_proxy_node(
    ProxyNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_proxy_node(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_verified_dns(
    VerifiedDns self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_verified_dns(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_proxy_node(
    List<ProxyNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_proxy_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_verified_dns(
    List<VerifiedDns> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_verified_dns(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_verified_dns(
    VerifiedDns? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_verified_dns(self, serializer);
    }
  }

  @protected
  void sse_encode_proxy_node(ProxyNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.rawUrl, serializer);
  }

  @protected
  void sse_encode_scanner_stats(ScannerStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.totalScanned, serializer);
    sse_encode_i_32(self.aliveCount, serializer);
    sse_encode_i_32(self.deadCount, serializer);
    sse_encode_bool(self.isRunning, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verified_dns(VerifiedDns self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ip, serializer);
    sse_encode_i_32(self.latencyMs, serializer);
    sse_encode_bool(self.worksSingbox, serializer);
    sse_encode_bool(self.worksTor, serializer);
    sse_encode_bool(self.worksPsiphon, serializer);
  }
}
