// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// گزارش تحلیلی هسته دوم بر اساس فرمول ریاضی: d(y, R)
class BehaviorAnalysisReport {
  final BigInt sampleCount;
  final double movingAverage;
  final double standardDeviation;
  final double expectedRangeLower;
  final double expectedRangeUpper;
  final double actualMeasuredValue;

  /// مقدار انحراف محاسبه‌شده دقیقاً طبق فرمول d(y, R)
  final double deviationValue;
  final DeviationSeverity severity;
  final bool isDegraded;
  final String alertMessage;

  const BehaviorAnalysisReport({
    required this.sampleCount,
    required this.movingAverage,
    required this.standardDeviation,
    required this.expectedRangeLower,
    required this.expectedRangeUpper,
    required this.actualMeasuredValue,
    required this.deviationValue,
    required this.severity,
    required this.isDegraded,
    required this.alertMessage,
  });

  @override
  int get hashCode =>
      sampleCount.hashCode ^
      movingAverage.hashCode ^
      standardDeviation.hashCode ^
      expectedRangeLower.hashCode ^
      expectedRangeUpper.hashCode ^
      actualMeasuredValue.hashCode ^
      deviationValue.hashCode ^
      severity.hashCode ^
      isDegraded.hashCode ^
      alertMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BehaviorAnalysisReport &&
          runtimeType == other.runtimeType &&
          sampleCount == other.sampleCount &&
          movingAverage == other.movingAverage &&
          standardDeviation == other.standardDeviation &&
          expectedRangeLower == other.expectedRangeLower &&
          expectedRangeUpper == other.expectedRangeUpper &&
          actualMeasuredValue == other.actualMeasuredValue &&
          deviationValue == other.deviationValue &&
          severity == other.severity &&
          isDegraded == other.isDegraded &&
          alertMessage == other.alertMessage;
}

/// خروجی استاندارد و کالیبره‌شده هسته اول برای تحویل به فلاتر و موتور Sing-box
class CalibratedConnectionProfile {
  final String targetHost;
  final int selectedPort;
  final bool enableTlsFragment;
  final bool enableRecordFragment;
  final String optimalDelayStr;
  final BigInt recommendedPaddingBytes;
  final ConnectionQualityMetrics qualityMetrics;

  /// آیا از حافظه یادگیری سریع (Fast-Path بدون معطلی تست) استفاده شد؟
  final bool isFastPathCached;

  /// سقف واقعی ظرفیت پکت دکل مخابراتی کاربر (Path MTU)
  final int optimalMtu;

  /// کران پایین بازه مورد انتظار برای هسته دوم (L)
  final double expectedLatencyLower;

  /// کران بالای بازه مورد انتظار برای هسته دوم (U)
  final double expectedLatencyUpper;

  const CalibratedConnectionProfile({
    required this.targetHost,
    required this.selectedPort,
    required this.enableTlsFragment,
    required this.enableRecordFragment,
    required this.optimalDelayStr,
    required this.recommendedPaddingBytes,
    required this.qualityMetrics,
    required this.isFastPathCached,
    required this.optimalMtu,
    required this.expectedLatencyLower,
    required this.expectedLatencyUpper,
  });

  @override
  int get hashCode =>
      targetHost.hashCode ^
      selectedPort.hashCode ^
      enableTlsFragment.hashCode ^
      enableRecordFragment.hashCode ^
      optimalDelayStr.hashCode ^
      recommendedPaddingBytes.hashCode ^
      qualityMetrics.hashCode ^
      isFastPathCached.hashCode ^
      optimalMtu.hashCode ^
      expectedLatencyLower.hashCode ^
      expectedLatencyUpper.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalibratedConnectionProfile &&
          runtimeType == other.runtimeType &&
          targetHost == other.targetHost &&
          selectedPort == other.selectedPort &&
          enableTlsFragment == other.enableTlsFragment &&
          enableRecordFragment == other.enableRecordFragment &&
          optimalDelayStr == other.optimalDelayStr &&
          recommendedPaddingBytes == other.recommendedPaddingBytes &&
          qualityMetrics == other.qualityMetrics &&
          isFastPathCached == other.isFastPathCached &&
          optimalMtu == other.optimalMtu &&
          expectedLatencyLower == other.expectedLatencyLower &&
          expectedLatencyUpper == other.expectedLatencyUpper;
}

/// شاخص‌های چندگانه برای ارزیابی جامع کیفیت اتصال
class ConnectionQualityMetrics {
  final double latencyMs;
  final double jitterMs;
  final double packetLossRatio;
  final double handshakeTimeMs;
  final double stabilityFactor;

  /// امتیاز کل محاسبه‌شده بر پایه وزن‌های هوشمند (از ۰ تا ۱۰۰)
  final double overallScore;

  const ConnectionQualityMetrics({
    required this.latencyMs,
    required this.jitterMs,
    required this.packetLossRatio,
    required this.handshakeTimeMs,
    required this.stabilityFactor,
    required this.overallScore,
  });

  @override
  int get hashCode =>
      latencyMs.hashCode ^
      jitterMs.hashCode ^
      packetLossRatio.hashCode ^
      handshakeTimeMs.hashCode ^
      stabilityFactor.hashCode ^
      overallScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionQualityMetrics &&
          runtimeType == other.runtimeType &&
          latencyMs == other.latencyMs &&
          jitterMs == other.jitterMs &&
          packetLossRatio == other.packetLossRatio &&
          handshakeTimeMs == other.handshakeTimeMs &&
          stabilityFactor == other.stabilityFactor &&
          overallScore == other.overallScore;
}

/// شدت انحراف رفتاری اتصال از خط استاندارد
enum DeviationSeverity { normal, warning, critical }
