device_id = "b8811a6c-8dc8-4d37-9788-bd4336a1e4c7"
access_token = "122dec04-f7cd-461b-a1f6-7d1231f1a553"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8c7a:40ab:d9f3:5955:275e"
wg_private_key = "yMt4BacFbKiKRcwriaeEw01CfZ4V98rL2E7cAZ7EPWk="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "DUjv"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
