device_id = "b6257fcc-efaa-4837-b35c-b70d7569b3b9"
access_token = "9ab4d291-5ec5-45ed-bbb9-c86c744b04ab"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:84d5:9fcb:5149:3f39:6001"
wg_private_key = "iCfnKhSSLE9971SDMDfXg89yVQMKJR968v+UkzoAfFY="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "NPRI"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.4"
