device_id = "d782b54c-e676-43f1-92fd-297a5988c7e5"
access_token = "b6df7225-f33f-4504-999a-ed2580d5ccfd"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8d86:c814:aeb6:6884:f385"
wg_private_key = "kMAh+lidiwAtZOMfiNouqgPb07KChpTH7mody6FXplE="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "5XfV"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.10"
