device_id = "1abe9d01-c05f-44af-87ed-6991f3d262d1"
access_token = "3ed521e5-51b1-415f-9a4f-bbe0c27c0161"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8312:fe56:7ae9:7092:5f7e"
wg_private_key = "wHSCvat2ZFS0hY0q35daXYbseQfmzOsfoCvowgbXhk8="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "yVm7"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.7"
