device_id = "79003e88-1da3-41a4-93df-02a0aad64ee8"
access_token = "3ff55001-8103-4627-b3d3-ab3d1dc0e844"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:89f9:e189:c739:7edf:1fe2"
wg_private_key = "qHTkgK6OOdZizt6TR/HVGqaTux20p/oeH8+bwvd7pH8="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "KDhs"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
