device_id = "b4279db4-13c8-440a-bd86-b65c7e430953"
access_token = "cc4a7e75-8d84-4486-accf-0b1d988255f7"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8b49:3647:3365:d029:923b"
wg_private_key = "UJfEqwSGUkeKlm+SYWEJgRcSbhzl7AwPAh6UTOUcnVY="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "xxld"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
