device_id = "0ab754e5-87a5-45fa-a484-5af9d47571c9"
access_token = "4c486d6b-f80b-42b6-a9a8-da96aa336bf4"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:82c6:a7f6:9049:4ebb:35b"
wg_private_key = "yMos3R5sRDYAyP/29UAfQUoip7PIOnKFLT/kGLV/XHg="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "DBAy"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.9"
