device_id = "06dfc538-910b-441e-b2b8-5281f68fa276"
access_token = "f98594df-53b3-4c8f-ac4c-4e2dcce07f5b"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8ee2:6eaa:6ef9:64e8:fcc4"
wg_private_key = "kJWaaYYL4KA/TmjSPvDDxLpMry+CJiTFBr4xU2JAUXI="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "meb6"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.2"
