device_id = "cec83215-814f-4da8-be9d-f3c6966949d6"
access_token = "2045b12c-1070-441c-a733-1f2efe3bac10"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:88a4:989d:801:f1ba:8df4"
wg_private_key = "CFJkVgzcv82XBMbhNOhwtWgaJm6G3CNEYzX0aNjkSXQ="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "6sXB"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.8"
