device_id = "7d315807-8ca0-49b1-9881-27fd4a680035"
access_token = "c78d32c3-51f8-44d9-9766-c9e3e8aaf600"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8de9:214e:8ecf:9b43:2e42"
wg_private_key = "4I2oJChowBNMwxEDCgxxvkFw3wdJLcIT2CujXDuZqXs="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "MhO5"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.4"
