device_id = "7fbf9702-e8fa-48e8-940c-9ce00456e7f7"
access_token = "f7196cdd-8da8-403d-a257-7904783c6935"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:89c7:abce:f5e5:b90:770c"
wg_private_key = "6NcUC6/wTcEz7LnJqLIGPMjtw7LgN5WvgwFtWtYMeXg="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "21f5"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.2"
