device_id = "53fd81f9-46f3-463c-bf20-6cc0e00911aa"
access_token = "c512f100-4fa5-4733-8e06-717f9cadfb7d"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8276:34e2:218e:9f70:beb0"
wg_private_key = "iB24HntnirslAYaCTyxF/rSBrGs4rsB+IGz+W4C0Kn8="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "CLwC"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.4"
