device_id = "09ccf089-c153-4837-a194-be7638bfc46c"
access_token = "9bddbd6d-9c0d-470f-9731-42492eea3f22"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:891b:592a:21ec:1591:2a9"
wg_private_key = "AN6YkoUYob0tNXJ/EM5NZmhOJnpylrYigzkwj2vvSUw="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "PvkG"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.5"
