device_id = "8d6520eb-d76f-40fa-b870-d7bb55f1dce4"
access_token = "36479634-ff90-47bf-9304-d1358b5831ec"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:819c:ed39:4f80:2574:8b60"
wg_private_key = "aOGUn/BQIsN08ISdB+hjqimHXaYJHhFrD3YjwjsA5Vg="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "NNi7"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.2"
