device_id = "6ec90ad8-19f1-4df2-b010-245eb28b9716"
access_token = "dfa1667b-b7ba-4e7f-9eb5-aac7cb18ad9d"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8c53:b412:a2ca:b226:fc1"
wg_private_key = "yLYWJAIHe6yOcPqoeQtzutdXfK7sm1NLK/FFNwRDlVU="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "A2Wa"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
