device_id = "4e73ec6c-148a-4a6f-bb5e-a2186e498b9f"
access_token = "8dd2204a-d71e-4605-bb23-ae56acd2f16c"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:844d:1b87:2780:f795:71c0"
wg_private_key = "MOCjsIf8iLWaeigaAnRBcCKST2ZR+L2/4zhGRXoBoXY="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "lEND"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.5"
