device_id = "b852910e-3a15-47d3-89c2-dc3d64ef4cd6"
access_token = "0bc2bdee-484c-4a8f-b8e5-cba8c01d490b"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8ec2:32ab:f654:bb4c:220b"
wg_private_key = "cMool8gu2HxIYPDPOcZPXG3iQB1iyNXm28Los3r3F08="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "HrKH"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.10"
