device_id = "37ada2c8-925d-482d-8770-780be0df9fc9"
access_token = "fdad0f8a-435e-4a48-a0d3-abd622641c86"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8e20:bb53:6dcf:7a71:d9cd"
wg_private_key = "6FAL+yrhUHlTXWNGzZyBwNotxkd+Ue1m/7aeZOCF0mM="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "V+T4"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.10"
