device_id = "3b2e4c34-9781-4f45-b002-5f3045550a59"
access_token = "da797f8b-81d8-45bc-8d4d-eea370ec80fc"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:81a2:2086:f4a8:174a:8e47"
wg_private_key = "UFmgnt18+NXuRRsjKE8FvRWerc0nDWuMnnJtJBfBSHM="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "LN68"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.3"
