device_id = "2d7ae63c-8acc-46f4-9711-e9660e9d1c5d"
access_token = "3f199767-23e4-4c8c-9dc5-6a546626ce9c"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:808a:15f2:ad84:d6ea:4a07"
wg_private_key = "EGXa2I4SrzTTU11xAIw+7Q7YyOXJjtOA6ysOPVri4U0="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "dhMw"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.4"
