device_id = "0f74a290-1349-4a90-895d-4fea5e05fae6"
access_token = "0eeecab1-ff3b-4e2b-b72c-2bb2469e222d"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:87fa:7857:4f96:d3e7:410"
wg_private_key = "CL/80M22iRkvaWWjC3radCIjAp76WOW2Qd9/O83DP3w="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "oQs7"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.8"
