device_id = "9ef47d7c-0622-4d7e-8897-18854b1af278"
access_token = "ed6fc077-1fd8-46bb-adab-7dc0dfb72f7d"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:84de:5210:9827:befd:a7aa"
wg_private_key = "4Ip3tGCag6oM71fP4RrFqVR9+zVSk1WoPFTodR3hRn0="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "dHiZ"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.10"
