device_id = "5659962d-2381-4cca-89d0-297682f12e39"
access_token = "b1b99660-94e0-49da-9429-f1c7cc939bbe"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8886:fbce:bcec:da5c:f87c"
wg_private_key = "YKVrd3CFH8SgORT6DmngNVXDRY418LoqydnmR6B1GmE="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "dQuL"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
