device_id = "c8f29e21-8a3b-4931-a409-8712f458f59d"
access_token = "eb20721d-ed6e-46e3-beb9-13bcbc863333"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8381:20a7:6865:f3fd:d102"
wg_private_key = "eG+xJRdO35ClbYaT92uZGNpze1GNtevHbSh9U9sFaVY="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "TAKj"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.7"
