device_id = "c704e2a0-b352-42ca-8dcd-297cbbc27d15"
access_token = "a1ce1479-947a-492d-8c0f-47c5cafb0d86"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:84a6:3f97:a4b2:9cc5:5b2a"
wg_private_key = "WGvbvZDYdOnfk0tCvwaOXlvI6IHDXhoXeqUtvolDhmU="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "nv/E"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.5"
