// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../smart_core_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assign_child_to_job`, `convert_link_to_outbound`, `ensure_watchdog_started`, `extract_ipv4_from_dns_payload`, `fetch_live_ech_key_via_socks5`, `find_atc_pool_dir`, `find_verified_emergency_ip`, `format_ech_to_pem_lines`, `get_active_upstream_proxy_addr`, `get_cached_or_fallback_ech`, `get_core2_instance`, `get_global_job_object`, `get_learning_engine`, `get_safe_work_dir`, `get_timestamp`, `handle_lan_client`, `init_panic_hook`, `load_deep_scan_ips`, `notify_windows_proxy_change`, `probe_dns_truth_dynamically`, `process_aether_line`, `process_psiphon_line`, `resolve_binary_path`, `scan_single_ip_ws`, `send_native_telemetry`, `set_windows_system_proxy`, `spawn_single_aether_mode`, `start_psiphon_core_internal`, `start_tor_core_internal`, `test_socks5_egress`, `validate_config_safety`, `verify_dnscrypt_truth`, `verify_gaming_dns_truth`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// ثبت و به‌روزرسانی آمار رادار زنده در فایل موقت فوق‌سبک
Future<void> updateRadarMetricsFile() =>
    RustLib.instance.api.crateApiSimpleUpdateRadarMetricsFile();

/// کشف خودکار سقف واقعی پکت دکل مخابراتی (PMTU) جهت مهار پکت‌لاس
Future<int> getOptimalCarrierMtu() =>
    RustLib.instance.api.crateApiSimpleGetOptimalCarrierMtu();

/// ذخیره منطقه زمانی اولیه سیستم و ست کردن تایم‌زون جدید متناسب با کشور آی‌پی
Future<String> syncTimezoneToCountry({required String countryCode}) => RustLib
    .instance
    .api
    .crateApiSimpleSyncTimezoneToCountry(countryCode: countryCode);

/// بازگرداندن فوری منطقه زمانی اولیه ویندوز (تهران) به محض قطع اتصال
Future<String> restoreOriginalTimezone() =>
    RustLib.instance.api.crateApiSimpleRestoreOriginalTimezone();

/// پاکسازی سراسری و فوق‌سریع تمامی پروسه‌های زامبی قبل از راه‌اندازی هر تونل
Future<void> killAllZombieCores() =>
    RustLib.instance.api.crateApiSimpleKillAllZombieCores();

Future<void> startAntiRstFilter() =>
    RustLib.instance.api.crateApiSimpleStartAntiRstFilter();

Future<void> stopAntiRstFilter() =>
    RustLib.instance.api.crateApiSimpleStopAntiRstFilter();

Future<bool> isDnsttRunning() =>
    RustLib.instance.api.crateApiSimpleIsDnsttRunning();

Future<String> startDnsttCore({
  String? binaryPath,
  required String dohUrl,
  required String pubkey,
  required String domain,
  required int localPort,
}) => RustLib.instance.api.crateApiSimpleStartDnsttCore(
  binaryPath: binaryPath,
  dohUrl: dohUrl,
  pubkey: pubkey,
  domain: domain,
  localPort: localPort,
);

Future<String> stopDnsttCore() =>
    RustLib.instance.api.crateApiSimpleStopDnsttCore();

Future<List<String>> findActiveResolversForDomain({
  required String targetDomain,
}) => RustLib.instance.api.crateApiSimpleFindActiveResolversForDomain(
  targetDomain: targetDomain,
);

Future<bool> isUdp2RawRunning() =>
    RustLib.instance.api.crateApiSimpleIsUdp2RawRunning();

Future<String> startUdp2RawCore({
  String? binaryPath,
  required String remoteAddr,
  required int localPort,
  String? key,
}) => RustLib.instance.api.crateApiSimpleStartUdp2RawCore(
  binaryPath: binaryPath,
  remoteAddr: remoteAddr,
  localPort: localPort,
  key: key,
);

Future<String> stopUdp2RawCore() =>
    RustLib.instance.api.crateApiSimpleStopUdp2RawCore();

Future<int> benchmarkAndOptimizeUdp2Raw({
  required String remoteHost,
  required int remotePort,
  String? binaryPath,
  String? key,
}) => RustLib.instance.api.crateApiSimpleBenchmarkAndOptimizeUdp2Raw(
  remoteHost: remoteHost,
  remotePort: remotePort,
  binaryPath: binaryPath,
  key: key,
);

Future<bool> isDnscryptRunning() =>
    RustLib.instance.api.crateApiSimpleIsDnscryptRunning();

Future<String> startDnscryptCore({String? binaryPath}) => RustLib.instance.api
    .crateApiSimpleStartDnscryptCore(binaryPath: binaryPath);

Future<String> stopDnscryptCore() =>
    RustLib.instance.api.crateApiSimpleStopDnscryptCore();

Future<bool> isGoodbyedpiRunning() =>
    RustLib.instance.api.crateApiSimpleIsGoodbyedpiRunning();

Future<String> startGoodbyedpiCore({
  required String binaryPath,
  required String args,
}) => RustLib.instance.api.crateApiSimpleStartGoodbyedpiCore(
  binaryPath: binaryPath,
  args: args,
);

Future<String> stopGoodbyedpiCore() =>
    RustLib.instance.api.crateApiSimpleStopGoodbyedpiCore();

Future<List<String>> getAllLocalIpAddresses() =>
    RustLib.instance.api.crateApiSimpleGetAllLocalIpAddresses();

Future<String> getLocalIpAddress() =>
    RustLib.instance.api.crateApiSimpleGetLocalIpAddress();

Future<String> startLanRelay({required int port}) =>
    RustLib.instance.api.crateApiSimpleStartLanRelay(port: port);

Future<String> stopLanRelay() =>
    RustLib.instance.api.crateApiSimpleStopLanRelay();

Future<bool> isLanRelayRunning() =>
    RustLib.instance.api.crateApiSimpleIsLanRelayRunning();

Future<int> getLanRelayPort() =>
    RustLib.instance.api.crateApiSimpleGetLanRelayPort();

Future<void> writeLog({
  required String level,
  required String tag,
  required String message,
}) => RustLib.instance.api.crateApiSimpleWriteLog(
  level: level,
  tag: tag,
  message: message,
);

Future<void> writeAppLog({
  required String level,
  required String tag,
  required String message,
}) => RustLib.instance.api.crateApiSimpleWriteAppLog(
  level: level,
  tag: tag,
  message: message,
);

Future<String> getLogFilePath() =>
    RustLib.instance.api.crateApiSimpleGetLogFilePath();

Future<String> openLogDirectory() =>
    RustLib.instance.api.crateApiSimpleOpenLogDirectory();

Future<String> clearLogFile() =>
    RustLib.instance.api.crateApiSimpleClearLogFile();

Future<bool> isConnected() => RustLib.instance.api.crateApiSimpleIsConnected();

Future<bool> isTorConnected() =>
    RustLib.instance.api.crateApiSimpleIsTorConnected();

Future<bool> isTorMasqueConnected() =>
    RustLib.instance.api.crateApiSimpleIsTorMasqueConnected();

Future<bool> isPsiphonConnected() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonConnected();

Future<bool> isPsiphonMasqueConnected() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonMasqueConnected();

Future<bool> isAetherConnected() =>
    RustLib.instance.api.crateApiSimpleIsAetherConnected();

Future<bool> isHybridConnected() =>
    RustLib.instance.api.crateApiSimpleIsHybridConnected();

Future<bool> isDnsActive() => RustLib.instance.api.crateApiSimpleIsDnsActive();

Future<bool> isSlipnetRunning() =>
    RustLib.instance.api.crateApiSimpleIsSlipnetRunning();

Future<bool> isSlipnetConnected() =>
    RustLib.instance.api.crateApiSimpleIsSlipnetConnected();

Future<String> getSlipnetStatusText() =>
    RustLib.instance.api.crateApiSimpleGetSlipnetStatusText();

Future<bool> isWhitednsRunning() =>
    RustLib.instance.api.crateApiSimpleIsWhitednsRunning();

Future<bool> isWhitednsConnected() =>
    RustLib.instance.api.crateApiSimpleIsWhitednsConnected();

Future<String> getWhitednsStatusText() =>
    RustLib.instance.api.crateApiSimpleGetWhitednsStatusText();

Future<int> getTorBootstrapProgress() =>
    RustLib.instance.api.crateApiSimpleGetTorBootstrapProgress();

Future<bool> isPsiphonBootstrapDone() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonBootstrapDone();

Future<String> getPsiphonStatusText() =>
    RustLib.instance.api.crateApiSimpleGetPsiphonStatusText();

Future<int> getAetherBootstrapProgress() =>
    RustLib.instance.api.crateApiSimpleGetAetherBootstrapProgress();

Future<bool> isAetherBootstrapDone() =>
    RustLib.instance.api.crateApiSimpleIsAetherBootstrapDone();

Future<String> getAetherStatusText() =>
    RustLib.instance.api.crateApiSimpleGetAetherStatusText();

Future<VerifiedDns?> verifyDnsIp({required String ip}) =>
    RustLib.instance.api.crateApiSimpleVerifyDnsIp(ip: ip);

Future<List<VerifiedDns>> runDnsRescueScan({String? customDnsList}) => RustLib
    .instance
    .api
    .crateApiSimpleRunDnsRescueScan(customDnsList: customDnsList);

Future<List<VerifiedDns>> getVaultDnsList() =>
    RustLib.instance.api.crateApiSimpleGetVaultDnsList();

Future<int> pingDnsServer({required String ip}) =>
    RustLib.instance.api.crateApiSimplePingDnsServer(ip: ip);

Future<int> pingProxyServer({required String host, required int port}) =>
    RustLib.instance.api.crateApiSimplePingProxyServer(host: host, port: port);

Future<String> setSystemDns({
  required String primary,
  required String secondary,
}) => RustLib.instance.api.crateApiSimpleSetSystemDns(
  primary: primary,
  secondary: secondary,
);

Future<String> resetSystemDns() =>
    RustLib.instance.api.crateApiSimpleResetSystemDns();

/// بررسی و تزریق خودکار هویت از استخر اکانت‌های ATC برای کاربران جدید
Future<void> ensureAetherIdentityFromPool() =>
    RustLib.instance.api.crateApiSimpleEnsureAetherIdentityFromPool();

Future<String> startAetherCore({
  required String binaryPath,
  required String mode,
  required String noize,
  String? warpKey,
  String? team,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartAetherCore(
  binaryPath: binaryPath,
  mode: mode,
  noize: noize,
  warpKey: warpKey,
  team: team,
  useSystemProxy: useSystemProxy,
);

Future<String> stopAetherCore() =>
    RustLib.instance.api.crateApiSimpleStopAetherCore();

Future<String> startHybridConnection({
  required String singboxPath,
  required String aetherPath,
  required ProxyNode selectedNode,
  required String aetherMode,
  required String aetherNoize,
  String? aetherWarpKey,
  String? aetherTeam,
  required bool useSystemProxy,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDotHost,
  String? utlsFingerprint,
}) => RustLib.instance.api.crateApiSimpleStartHybridConnection(
  singboxPath: singboxPath,
  aetherPath: aetherPath,
  selectedNode: selectedNode,
  aetherMode: aetherMode,
  aetherNoize: aetherNoize,
  aetherWarpKey: aetherWarpKey,
  aetherTeam: aetherTeam,
  useSystemProxy: useSystemProxy,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDotHost: dnsDotHost,
  utlsFingerprint: utlsFingerprint,
);

Future<String> stopHybridConnection() =>
    RustLib.instance.api.crateApiSimpleStopHybridConnection();

Future<String> startRedcloudPipeline({
  required String rawUrl,
  String? singboxPath,
  String? aetherPath,
  String? psiphonPath,
  String? goodbyedpiPath,
}) => RustLib.instance.api.crateApiSimpleStartRedcloudPipeline(
  rawUrl: rawUrl,
  singboxPath: singboxPath,
  aetherPath: aetherPath,
  psiphonPath: psiphonPath,
  goodbyedpiPath: goodbyedpiPath,
);

Future<String> stopRedcloudPipeline() =>
    RustLib.instance.api.crateApiSimpleStopRedcloudPipeline();

Future<SlipNetProfile> parseSlipnetUri({required String rawUri}) =>
    RustLib.instance.api.crateApiSimpleParseSlipnetUri(rawUri: rawUri);

Future<String> startSlipnetCore({
  String? binaryPath,
  required String domain,
  required String pubkey,
  required String tunnelType,
  required String transport,
  required String resolvers,
  required int localPort,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartSlipnetCore(
  binaryPath: binaryPath,
  domain: domain,
  pubkey: pubkey,
  tunnelType: tunnelType,
  transport: transport,
  resolvers: resolvers,
  localPort: localPort,
  useSystemProxy: useSystemProxy,
);

Future<String> stopSlipnetCore() =>
    RustLib.instance.api.crateApiSimpleStopSlipnetCore();

Future<String> startWhitednsCore({
  String? binaryPath,
  required String domain,
  required String pubkey,
  required String engine,
  required String preset,
  required String resolvers,
  required int localPort,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartWhitednsCore(
  binaryPath: binaryPath,
  domain: domain,
  pubkey: pubkey,
  engine: engine,
  preset: preset,
  resolvers: resolvers,
  localPort: localPort,
  useSystemProxy: useSystemProxy,
);

Future<String> stopWhitednsCore() =>
    RustLib.instance.api.crateApiSimpleStopWhitednsCore();

Future<String> startTorCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartTorCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

Future<String> startTorOverMasque({
  required String torPath,
  required String aetherPath,
  required String countryCode,
  required String aetherMode,
  required String aetherNoize,
  String? aetherWarpKey,
  String? aetherTeam,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartTorOverMasque(
  torPath: torPath,
  aetherPath: aetherPath,
  countryCode: countryCode,
  aetherMode: aetherMode,
  aetherNoize: aetherNoize,
  aetherWarpKey: aetherWarpKey,
  aetherTeam: aetherTeam,
  useSystemProxy: useSystemProxy,
);

Future<String> stopTorOverMasque() =>
    RustLib.instance.api.crateApiSimpleStopTorOverMasque();

Future<String> stopTorCore() =>
    RustLib.instance.api.crateApiSimpleStopTorCore();

Future<String> startPsiphonCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartPsiphonCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

Future<String> startPsiphonOverMasque({
  required String psiphonPath,
  required String aetherPath,
  required String countryCode,
  required String aetherMode,
  required String aetherNoize,
  String? aetherWarpKey,
  String? aetherTeam,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartPsiphonOverMasque(
  psiphonPath: psiphonPath,
  aetherPath: aetherPath,
  countryCode: countryCode,
  aetherMode: aetherMode,
  aetherNoize: aetherNoize,
  aetherWarpKey: aetherWarpKey,
  aetherTeam: aetherTeam,
  useSystemProxy: useSystemProxy,
);

Future<String> stopPsiphonOverMasque() =>
    RustLib.instance.api.crateApiSimpleStopPsiphonOverMasque();

Future<String> stopPsiphonCore() =>
    RustLib.instance.api.crateApiSimpleStopPsiphonCore();

Future<void> stopCloudflareScanner() =>
    RustLib.instance.api.crateApiSimpleStopCloudflareScanner();

Future<ScannerStats> getScannerStats() =>
    RustLib.instance.api.crateApiSimpleGetScannerStats();

Future<List<ProxyNode>> runCloudflareScanner({
  required String uuid,
  required String path,
  required String worker,
  required String scanMode,
  required bool earlyStop,
}) => RustLib.instance.api.crateApiSimpleRunCloudflareScanner(
  uuid: uuid,
  path: path,
  worker: worker,
  scanMode: scanMode,
  earlyStop: earlyStop,
);

Future<String> startProxyWithNode({
  required String binaryPath,
  required ProxyNode selectedNode,
  required bool useSystemProxy,
  String? customSni,
  required bool enableFragment,
  required bool enableRecordFragment,
  String? tlsSpoof,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDohUrl,
  String? dnsDotHost,
  String? utlsFingerprint,
  String? fragmentFallbackDelay,
}) => RustLib.instance.api.crateApiSimpleStartProxyWithNode(
  binaryPath: binaryPath,
  selectedNode: selectedNode,
  useSystemProxy: useSystemProxy,
  customSni: customSni,
  enableFragment: enableFragment,
  enableRecordFragment: enableRecordFragment,
  tlsSpoof: tlsSpoof,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDohUrl: dnsDohUrl,
  dnsDotHost: dnsDotHost,
  utlsFingerprint: utlsFingerprint,
  fragmentFallbackDelay: fragmentFallbackDelay,
);

Future<String> stopProxyCore() =>
    RustLib.instance.api.crateApiSimpleStopProxyCore();

Future<List<ProxyNode>> parseImportLinks({required String input}) =>
    RustLib.instance.api.crateApiSimpleParseImportLinks(input: input);

/// کالیبراسیون و بهینه‌سازی زنده یک کانفیگ با موتور یادگیری خودآموز (MAB Learning)
Future<CalibratedConnectionProfile> calibrateAndOptimizeNode({
  required String rawUrl,
}) =>
    RustLib.instance.api.crateApiSimpleCalibrateAndOptimizeNode(rawUrl: rawUrl);

/// ثبت نمونه واقعی اتصال در هسته دوم و محاسبه انحراف ریاضی d(y, R)
Future<BehaviorAnalysisReport> recordLiveConnectionMetric({
  required double measuredLatencyMs,
}) => RustLib.instance.api.crateApiSimpleRecordLiveConnectionMetric(
  measuredLatencyMs: measuredLatencyMs,
);

/// اتصال هوشمند و کاملاً خودکار: کالیبراسیون با هسته اول و سپس برقراری تونل
Future<CalibratedConnectionProfile> startSmartOptimizedProxy({
  required String binaryPath,
  required ProxyNode selectedNode,
  required bool useSystemProxy,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDotHost,
}) => RustLib.instance.api.crateApiSimpleStartSmartOptimizedProxy(
  binaryPath: binaryPath,
  selectedNode: selectedNode,
  useSystemProxy: useSystemProxy,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDotHost: dnsDotHost,
);

/// خوددرمانگری خودکار: جهش به استراتژی ضد اختلال بدون نیاز به دخالت کاربر
Future<CalibratedConnectionProfile> autoHealAndRecalibrate({
  required String binaryPath,
  required ProxyNode selectedNode,
  required bool useSystemProxy,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDotHost,
}) => RustLib.instance.api.crateApiSimpleAutoHealAndRecalibrate(
  binaryPath: binaryPath,
  selectedNode: selectedNode,
  useSystemProxy: useSystemProxy,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDotHost: dnsDotHost,
);

/// استعلام بهترین حالت یادگرفته‌شده برای یک پروتکل از حافظه شبکه (Fast-Path برای اِتر، تور و سایفون)
Future<String?> getSuggestedProtocolMode({required String protocol}) => RustLib
    .instance
    .api
    .crateApiSimpleGetSuggestedProtocolMode(protocol: protocol);

/// ساخت پروفایل کالیبراسیون و تله‌متری واقعی برای پروتکل‌های غیر VLESS
Future<CalibratedConnectionProfile> createProtocolCalibratedProfile({
  required String protocolName,
  required String modeOrRegion,
  required int localPort,
  required double measuredLatencyMs,
  required bool isFastPath,
}) => RustLib.instance.api.crateApiSimpleCreateProtocolCalibratedProfile(
  protocolName: protocolName,
  modeOrRegion: modeOrRegion,
  localPort: localPort,
  measuredLatencyMs: measuredLatencyMs,
  isFastPath: isFastPath,
);

/// تست گروهی استخر DNSهای گیمینگ روی دامنه‌های احراز هویت بازی انتخاب‌شده
Future<List<GamingDnsReport>> testAndVerifyGamingDns({
  required List<String> domains,
}) =>
    RustLib.instance.api.crateApiSimpleTestAndVerifyGamingDns(domains: domains);

/// اندازه‌گیری دقیق و چندمرحله‌ای پینگ و نوسان (Jitter) روی گیت‌وی‌های منطقه‌ای
Future<GamingBenchmarkResult> benchmarkGamingRegions({
  required String preferredRegion,
}) => RustLib.instance.api.crateApiSimpleBenchmarkGamingRegions(
  preferredRegion: preferredRegion,
);

/// اعمال تنظیمات شتاب‌دهنده کرنل ویندوز برای پکت‌لاس صفر (BBR + TcpAckFrequency=1)
Future<void> applyWindowsGamingKernelTweaks() =>
    RustLib.instance.api.crateApiSimpleApplyWindowsGamingKernelTweaks();

/// شروع بوستر گیمینگ با روتینگ اختصاصی پروسه بازی و قفل سشن (Anti-Ban Session Lock)
Future<String> startGamingBoost({
  required String singboxPath,
  required String aetherPath,
  required GamingBoostConfig config,
}) => RustLib.instance.api.crateApiSimpleStartGamingBoost(
  singboxPath: singboxPath,
  aetherPath: aetherPath,
  config: config,
);

/// متوقف‌سازی کامل بوستر گیمینگ و بازنشانی کارت‌های شبکه
Future<String> stopGamingBoost() =>
    RustLib.instance.api.crateApiSimpleStopGamingBoost();

Future<bool> isGamingBoostActive() =>
    RustLib.instance.api.crateApiSimpleIsGamingBoostActive();

/// استعلام زنده پارامترهای مانیتورینگ گیمینگ برای نمایش در HUD فلاتر
Future<GamingLiveMetrics> getGamingLiveMetrics() =>
    RustLib.instance.api.crateApiSimpleGetGamingLiveMetrics();

/// دستور توقف آنی اسکنر دی‌ان‌اس
Future<void> stopDnsDomainScanner() =>
    RustLib.instance.api.crateApiSimpleStopDnsDomainScanner();

/// دریافت بلادرنگ آمار پیشرفت اسکنر دی‌ان‌اس
Future<DnsScannerProgress> getDnsScannerProgress() =>
    RustLib.instance.api.crateApiSimpleGetDnsScannerProgress();

/// اسکن موازی، هوشمند و تطبیقی دی‌ان‌اس‌ها متناسب با سخت‌افزار کاربر و قابلیت لغو زنده
Future<List<ScannedDnsResult>> scanAndRankDnsForTarget({
  required String target,
  int? concurrency,
}) => RustLib.instance.api.crateApiSimpleScanAndRankDnsForTarget(
  target: target,
  concurrency: concurrency,
);

class DnsScannerProgress {
  final int totalServers;
  final int scannedServers;
  final int aliveServers;
  final int deadServers;
  final int progressPercent;
  final bool isRunning;

  const DnsScannerProgress({
    required this.totalServers,
    required this.scannedServers,
    required this.aliveServers,
    required this.deadServers,
    required this.progressPercent,
    required this.isRunning,
  });

  @override
  int get hashCode =>
      totalServers.hashCode ^
      scannedServers.hashCode ^
      aliveServers.hashCode ^
      deadServers.hashCode ^
      progressPercent.hashCode ^
      isRunning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DnsScannerProgress &&
          runtimeType == other.runtimeType &&
          totalServers == other.totalServers &&
          scannedServers == other.scannedServers &&
          aliveServers == other.aliveServers &&
          deadServers == other.deadServers &&
          progressPercent == other.progressPercent &&
          isRunning == other.isRunning;
}

class GamingBenchmarkResult {
  final String regionName;
  final String regionCode;
  final String targetIp;
  final int minPingMs;
  final int maxPingMs;
  final int avgPingMs;
  final int jitterMs;
  final double packetLossPercent;
  final String recommendedMode;
  final String recommendedNoize;

  const GamingBenchmarkResult({
    required this.regionName,
    required this.regionCode,
    required this.targetIp,
    required this.minPingMs,
    required this.maxPingMs,
    required this.avgPingMs,
    required this.jitterMs,
    required this.packetLossPercent,
    required this.recommendedMode,
    required this.recommendedNoize,
  });

  @override
  int get hashCode =>
      regionName.hashCode ^
      regionCode.hashCode ^
      targetIp.hashCode ^
      minPingMs.hashCode ^
      maxPingMs.hashCode ^
      avgPingMs.hashCode ^
      jitterMs.hashCode ^
      packetLossPercent.hashCode ^
      recommendedMode.hashCode ^
      recommendedNoize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamingBenchmarkResult &&
          runtimeType == other.runtimeType &&
          regionName == other.regionName &&
          regionCode == other.regionCode &&
          targetIp == other.targetIp &&
          minPingMs == other.minPingMs &&
          maxPingMs == other.maxPingMs &&
          avgPingMs == other.avgPingMs &&
          jitterMs == other.jitterMs &&
          packetLossPercent == other.packetLossPercent &&
          recommendedMode == other.recommendedMode &&
          recommendedNoize == other.recommendedNoize;
}

class GamingBoostConfig {
  final String gameId;
  final String gameName;
  final List<String> executables;
  final List<String> authDomains;
  final String preferredRegion;
  final bool enableKernelTweaks;
  final String dnsMode;

  const GamingBoostConfig({
    required this.gameId,
    required this.gameName,
    required this.executables,
    required this.authDomains,
    required this.preferredRegion,
    required this.enableKernelTweaks,
    required this.dnsMode,
  });

  @override
  int get hashCode =>
      gameId.hashCode ^
      gameName.hashCode ^
      executables.hashCode ^
      authDomains.hashCode ^
      preferredRegion.hashCode ^
      enableKernelTweaks.hashCode ^
      dnsMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamingBoostConfig &&
          runtimeType == other.runtimeType &&
          gameId == other.gameId &&
          gameName == other.gameName &&
          executables == other.executables &&
          authDomains == other.authDomains &&
          preferredRegion == other.preferredRegion &&
          enableKernelTweaks == other.enableKernelTweaks &&
          dnsMode == other.dnsMode;
}

class GamingDnsReport {
  final String providerName;
  final String dnsIp;
  final int latencyMs;
  final bool isTruthVerified;
  final String resolvedIp;

  const GamingDnsReport({
    required this.providerName,
    required this.dnsIp,
    required this.latencyMs,
    required this.isTruthVerified,
    required this.resolvedIp,
  });

  @override
  int get hashCode =>
      providerName.hashCode ^
      dnsIp.hashCode ^
      latencyMs.hashCode ^
      isTruthVerified.hashCode ^
      resolvedIp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamingDnsReport &&
          runtimeType == other.runtimeType &&
          providerName == other.providerName &&
          dnsIp == other.dnsIp &&
          latencyMs == other.latencyMs &&
          isTruthVerified == other.isTruthVerified &&
          resolvedIp == other.resolvedIp;
}

class GamingLiveMetrics {
  final bool isActive;
  final String gameName;
  final int currentPingMs;
  final int currentJitterMs;
  final int rstPacketsDefended;
  final bool isSessionLocked;
  final String activeRegion;

  const GamingLiveMetrics({
    required this.isActive,
    required this.gameName,
    required this.currentPingMs,
    required this.currentJitterMs,
    required this.rstPacketsDefended,
    required this.isSessionLocked,
    required this.activeRegion,
  });

  @override
  int get hashCode =>
      isActive.hashCode ^
      gameName.hashCode ^
      currentPingMs.hashCode ^
      currentJitterMs.hashCode ^
      rstPacketsDefended.hashCode ^
      isSessionLocked.hashCode ^
      activeRegion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamingLiveMetrics &&
          runtimeType == other.runtimeType &&
          isActive == other.isActive &&
          gameName == other.gameName &&
          currentPingMs == other.currentPingMs &&
          currentJitterMs == other.currentJitterMs &&
          rstPacketsDefended == other.rstPacketsDefended &&
          isSessionLocked == other.isSessionLocked &&
          activeRegion == other.activeRegion;
}

class ProxyNode {
  final String name;
  final String protocol;
  final String rawUrl;

  const ProxyNode({
    required this.name,
    required this.protocol,
    required this.rawUrl,
  });

  @override
  int get hashCode => name.hashCode ^ protocol.hashCode ^ rawUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          protocol == other.protocol &&
          rawUrl == other.rawUrl;
}

class ScannedDnsResult {
  final String dnsName;
  final String primaryIp;
  final int latencyMs;
  final String resolvedIp;
  final bool isGenuine;

  const ScannedDnsResult({
    required this.dnsName,
    required this.primaryIp,
    required this.latencyMs,
    required this.resolvedIp,
    required this.isGenuine,
  });

  @override
  int get hashCode =>
      dnsName.hashCode ^
      primaryIp.hashCode ^
      latencyMs.hashCode ^
      resolvedIp.hashCode ^
      isGenuine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScannedDnsResult &&
          runtimeType == other.runtimeType &&
          dnsName == other.dnsName &&
          primaryIp == other.primaryIp &&
          latencyMs == other.latencyMs &&
          resolvedIp == other.resolvedIp &&
          isGenuine == other.isGenuine;
}

class ScannerStats {
  final int totalScanned;
  final int aliveCount;
  final int deadCount;
  final bool isRunning;

  const ScannerStats({
    required this.totalScanned,
    required this.aliveCount,
    required this.deadCount,
    required this.isRunning,
  });

  @override
  int get hashCode =>
      totalScanned.hashCode ^
      aliveCount.hashCode ^
      deadCount.hashCode ^
      isRunning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScannerStats &&
          runtimeType == other.runtimeType &&
          totalScanned == other.totalScanned &&
          aliveCount == other.aliveCount &&
          deadCount == other.deadCount &&
          isRunning == other.isRunning;
}

class SlipNetProfile {
  final String name;
  final String tunnelType;
  final String domain;
  final String publicKey;
  final String dnsTransport;
  final String resolvers;

  const SlipNetProfile({
    required this.name,
    required this.tunnelType,
    required this.domain,
    required this.publicKey,
    required this.dnsTransport,
    required this.resolvers,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      tunnelType.hashCode ^
      domain.hashCode ^
      publicKey.hashCode ^
      dnsTransport.hashCode ^
      resolvers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlipNetProfile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          tunnelType == other.tunnelType &&
          domain == other.domain &&
          publicKey == other.publicKey &&
          dnsTransport == other.dnsTransport &&
          resolvers == other.resolvers;
}

/// مدل داده دی‌ان‌اس‌های تاییدشده و ضد مسمومیت در مخزن پنهان
class VerifiedDns {
  final String ip;
  final int latencyMs;
  final bool worksSingbox;
  final bool worksTor;
  final bool worksPsiphon;

  const VerifiedDns({
    required this.ip,
    required this.latencyMs,
    required this.worksSingbox,
    required this.worksTor,
    required this.worksPsiphon,
  });

  @override
  int get hashCode =>
      ip.hashCode ^
      latencyMs.hashCode ^
      worksSingbox.hashCode ^
      worksTor.hashCode ^
      worksPsiphon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifiedDns &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          latencyMs == other.latencyMs &&
          worksSingbox == other.worksSingbox &&
          worksTor == other.worksTor &&
          worksPsiphon == other.worksPsiphon;
}
