// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_link_to_outbound`, `scan_single_ip`, `set_windows_system_proxy`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<bool> isConnected() => RustLib.instance.api.crateApiSimpleIsConnected();

Future<bool> isTorConnected() =>
    RustLib.instance.api.crateApiSimpleIsTorConnected();

Future<bool> isPsiphonConnected() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonConnected();

Future<bool> isDnsActive() => RustLib.instance.api.crateApiSimpleIsDnsActive();

/// دریافت درصد پیشرفت فعلی فرآیند بوت‌استرپ تور توسط فلاتر
Future<int> getTorBootstrapProgress() =>
    RustLib.instance.api.crateApiSimpleGetTorBootstrapProgress();

/// بررسی اینکه آیا اتصال سایفون به سرورهای خارجی به طور واقعی برقرار شده است یا خیر
Future<bool> isPsiphonBootstrapDone() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonBootstrapDone();

/// پینگ سریع سرور دی‌ان‌اس روی پورت ۵۳
Future<int> pingDnsServer({required String ip}) =>
    RustLib.instance.api.crateApiSimplePingDnsServer(ip: ip);

/// پینگ سریع و واقعی آدرس سرور پروکسی روی پورت مقصد با اندازه گیری لاتنسی دست دهی TCP
Future<int> pingProxyServer({required String host, required int port}) =>
    RustLib.instance.api.crateApiSimplePingProxyServer(host: host, port: port);

/// اعمال دی‌ان‌اس انتخابی کاربر روی تمام کارت‌های شبکه فعال ویندوز با پاورشل بومی
Future<String> setSystemDns({
  required String primary,
  required String secondary,
}) => RustLib.instance.api.crateApiSimpleSetSystemDns(
  primary: primary,
  secondary: secondary,
);

/// بازنشانی تنظیمات دی‌ان‌اس سیستم‌عامل به حالت خودکار (DHCP)
Future<String> resetSystemDns() =>
    RustLib.instance.api.crateApiSimpleResetSystemDns();

/// شروع به کار هسته تور به همراه HTTPTunnelPort مجزا جهت رفع کامل نشت DNS
Future<String> startTorCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartTorCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

/// متوقف کردن کامل شبکه تور
Future<String> stopTorCore() =>
    RustLib.instance.api.crateApiSimpleStopTorCore();

/// شروع به کار هسته بومی سایفون به همراه ساخت پورت بومی HTTP Proxy جهت مهار نشت DNS
Future<String> startPsiphonCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartPsiphonCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

/// متوقف کردن کامل شبکه سایفون
Future<String> stopPsiphonCore() =>
    RustLib.instance.api.crateApiSimpleStopPsiphonCore();

/// شروع اسکن چندنخی آی‌پی‌های کلودفلر
Future<List<ProxyNode>> runCloudflareScanner({
  required String uuid,
  required String path,
  required String worker,
}) => RustLib.instance.api.crateApiSimpleRunCloudflareScanner(
  uuid: uuid,
  path: path,
  worker: worker,
);

/// اجرای پروکسی سنگ‌باکس با هدایت قطعی خروجی‌ها به Stdio::null جهت مخفی‌سازی کامل و بی‌صدا
Future<String> startProxyWithNode({
  required String binaryPath,
  required ProxyNode selectedNode,
  required bool useSystemProxy,
  String? customSni,
  required bool enableFragment,
  required bool enableRecordFragment,
  String? tlsSpoof,
  required bool useTunMode,
}) => RustLib.instance.api.crateApiSimpleStartProxyWithNode(
  binaryPath: binaryPath,
  selectedNode: selectedNode,
  useSystemProxy: useSystemProxy,
  customSni: customSni,
  enableFragment: enableFragment,
  enableRecordFragment: enableRecordFragment,
  tlsSpoof: tlsSpoof,
  useTunMode: useTunMode,
);

/// قطع پروکسی و بازگردانی تنظیمات پروکسی سیستم‌عامل به حالت اول
Future<String> stopProxyCore() =>
    RustLib.instance.api.crateApiSimpleStopProxyCore();

/// پردازش اولیه ورودی‌های لینک‌ها
Future<List<ProxyNode>> parseImportLinks({required String input}) =>
    RustLib.instance.api.crateApiSimpleParseImportLinks(input: input);

class ProxyNode {
  final String name;
  final String protocol;
  final String rawUrl;

  const ProxyNode({
    required this.name,
    required this.protocol,
    required this.rawUrl,
  });

  @override
  int get hashCode => name.hashCode ^ protocol.hashCode ^ rawUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          protocol == other.protocol &&
          rawUrl == other.rawUrl;
}
