// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assign_child_to_job`, `convert_link_to_outbound`, `get_global_job_object`, `get_safe_work_dir`, `load_deep_scan_ips`, `notify_windows_proxy_change`, `process_aether_line`, `process_psiphon_line`, `resolve_binary_path`, `scan_single_ip_ws`, `set_windows_system_proxy`, `spawn_single_aether_mode`, `start_psiphon_core_internal`, `start_tor_core_internal`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<bool> isConnected() => RustLib.instance.api.crateApiSimpleIsConnected();

Future<bool> isTorConnected() =>
    RustLib.instance.api.crateApiSimpleIsTorConnected();

Future<bool> isTorMasqueConnected() =>
    RustLib.instance.api.crateApiSimpleIsTorMasqueConnected();

Future<bool> isPsiphonConnected() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonConnected();

Future<bool> isPsiphonMasqueConnected() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonMasqueConnected();

Future<bool> isAetherConnected() =>
    RustLib.instance.api.crateApiSimpleIsAetherConnected();

Future<bool> isHybridConnected() =>
    RustLib.instance.api.crateApiSimpleIsHybridConnected();

Future<bool> isDnsActive() => RustLib.instance.api.crateApiSimpleIsDnsActive();

Future<int> getTorBootstrapProgress() =>
    RustLib.instance.api.crateApiSimpleGetTorBootstrapProgress();

Future<bool> isPsiphonBootstrapDone() =>
    RustLib.instance.api.crateApiSimpleIsPsiphonBootstrapDone();

Future<String> getPsiphonStatusText() =>
    RustLib.instance.api.crateApiSimpleGetPsiphonStatusText();

Future<int> getAetherBootstrapProgress() =>
    RustLib.instance.api.crateApiSimpleGetAetherBootstrapProgress();

Future<bool> isAetherBootstrapDone() =>
    RustLib.instance.api.crateApiSimpleIsAetherBootstrapDone();

Future<String> getAetherStatusText() =>
    RustLib.instance.api.crateApiSimpleGetAetherStatusText();

/// اسکنر واقعی لایه ۷ با غربالگری و فیلتر مسمومیت DNS ایران
Future<VerifiedDns?> verifyDnsIp({required String ip}) =>
    RustLib.instance.api.crateApiSimpleVerifyDnsIp(ip: ip);

/// اجرای اسکن خوددرمانگر و اضطراری DNS و ذخیره در مخزن پنهان
Future<List<VerifiedDns>> runDnsRescueScan({String? customDnsList}) => RustLib
    .instance
    .api
    .crateApiSimpleRunDnsRescueScan(customDnsList: customDnsList);

/// دریافت لیست دی‌ان‌اس‌های تمیز از مخزن پنهان
Future<List<VerifiedDns>> getVaultDnsList() =>
    RustLib.instance.api.crateApiSimpleGetVaultDnsList();

Future<int> pingDnsServer({required String ip}) =>
    RustLib.instance.api.crateApiSimplePingDnsServer(ip: ip);

Future<int> pingProxyServer({required String host, required int port}) =>
    RustLib.instance.api.crateApiSimplePingProxyServer(host: host, port: port);

Future<String> setSystemDns({
  required String primary,
  required String secondary,
}) => RustLib.instance.api.crateApiSimpleSetSystemDns(
  primary: primary,
  secondary: secondary,
);

Future<String> resetSystemDns() =>
    RustLib.instance.api.crateApiSimpleResetSystemDns();

Future<String> startAetherCore({
  required String binaryPath,
  required String mode,
  required String noize,
  String? warpKey,
  String? team,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartAetherCore(
  binaryPath: binaryPath,
  mode: mode,
  noize: noize,
  warpKey: warpKey,
  team: team,
  useSystemProxy: useSystemProxy,
);

Future<String> stopAetherCore() =>
    RustLib.instance.api.crateApiSimpleStopAetherCore();

Future<String> startHybridConnection({
  required String singboxPath,
  required String aetherPath,
  required ProxyNode selectedNode,
  required String aetherMode,
  required String aetherNoize,
  String? aetherWarpKey,
  String? aetherTeam,
  required bool useSystemProxy,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDotHost,
  String? utlsFingerprint,
}) => RustLib.instance.api.crateApiSimpleStartHybridConnection(
  singboxPath: singboxPath,
  aetherPath: aetherPath,
  selectedNode: selectedNode,
  aetherMode: aetherMode,
  aetherNoize: aetherNoize,
  aetherWarpKey: aetherWarpKey,
  aetherTeam: aetherTeam,
  useSystemProxy: useSystemProxy,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDotHost: dnsDotHost,
  utlsFingerprint: utlsFingerprint,
);

Future<String> stopHybridConnection() =>
    RustLib.instance.api.crateApiSimpleStopHybridConnection();

Future<String> startTorCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartTorCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

Future<String> startTorOverMasque({
  required String torPath,
  required String aetherPath,
  required String countryCode,
  required String aetherMode,
  required String aetherNoize,
  String? aetherWarpKey,
  String? aetherTeam,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartTorOverMasque(
  torPath: torPath,
  aetherPath: aetherPath,
  countryCode: countryCode,
  aetherMode: aetherMode,
  aetherNoize: aetherNoize,
  aetherWarpKey: aetherWarpKey,
  aetherTeam: aetherTeam,
  useSystemProxy: useSystemProxy,
);

Future<String> stopTorOverMasque() =>
    RustLib.instance.api.crateApiSimpleStopTorOverMasque();

Future<String> stopTorCore() =>
    RustLib.instance.api.crateApiSimpleStopTorCore();

Future<String> startPsiphonCore({
  required String binaryPath,
  required String countryCode,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartPsiphonCore(
  binaryPath: binaryPath,
  countryCode: countryCode,
  useSystemProxy: useSystemProxy,
);

Future<String> startPsiphonOverMasque({
  required String psiphonPath,
  required String aetherPath,
  required String countryCode,
  required String aetherMode,
  required String aetherNoize,
  String? aetherWarpKey,
  String? aetherTeam,
  required bool useSystemProxy,
}) => RustLib.instance.api.crateApiSimpleStartPsiphonOverMasque(
  psiphonPath: psiphonPath,
  aetherPath: aetherPath,
  countryCode: countryCode,
  aetherMode: aetherMode,
  aetherNoize: aetherNoize,
  aetherWarpKey: aetherWarpKey,
  aetherTeam: aetherTeam,
  useSystemProxy: useSystemProxy,
);

Future<String> stopPsiphonOverMasque() =>
    RustLib.instance.api.crateApiSimpleStopPsiphonOverMasque();

Future<String> stopPsiphonCore() =>
    RustLib.instance.api.crateApiSimpleStopPsiphonCore();

Future<void> stopCloudflareScanner() =>
    RustLib.instance.api.crateApiSimpleStopCloudflareScanner();

Future<ScannerStats> getScannerStats() =>
    RustLib.instance.api.crateApiSimpleGetScannerStats();

Future<List<ProxyNode>> runCloudflareScanner({
  required String uuid,
  required String path,
  required String worker,
  required String scanMode,
  required bool earlyStop,
}) => RustLib.instance.api.crateApiSimpleRunCloudflareScanner(
  uuid: uuid,
  path: path,
  worker: worker,
  scanMode: scanMode,
  earlyStop: earlyStop,
);

Future<String> startProxyWithNode({
  required String binaryPath,
  required ProxyNode selectedNode,
  required bool useSystemProxy,
  String? customSni,
  required bool enableFragment,
  required bool enableRecordFragment,
  String? tlsSpoof,
  required bool useTunMode,
  required String dnsType,
  required String dnsPrimary,
  required String dnsSecondary,
  String? dnsDohUrl,
  String? dnsDotHost,
  String? utlsFingerprint,
  String? fragmentFallbackDelay,
}) => RustLib.instance.api.crateApiSimpleStartProxyWithNode(
  binaryPath: binaryPath,
  selectedNode: selectedNode,
  useSystemProxy: useSystemProxy,
  customSni: customSni,
  enableFragment: enableFragment,
  enableRecordFragment: enableRecordFragment,
  tlsSpoof: tlsSpoof,
  useTunMode: useTunMode,
  dnsType: dnsType,
  dnsPrimary: dnsPrimary,
  dnsSecondary: dnsSecondary,
  dnsDohUrl: dnsDohUrl,
  dnsDotHost: dnsDotHost,
  utlsFingerprint: utlsFingerprint,
  fragmentFallbackDelay: fragmentFallbackDelay,
);

Future<String> stopProxyCore() =>
    RustLib.instance.api.crateApiSimpleStopProxyCore();

Future<List<ProxyNode>> parseImportLinks({required String input}) =>
    RustLib.instance.api.crateApiSimpleParseImportLinks(input: input);

class ProxyNode {
  final String name;
  final String protocol;
  final String rawUrl;

  const ProxyNode({
    required this.name,
    required this.protocol,
    required this.rawUrl,
  });

  @override
  int get hashCode => name.hashCode ^ protocol.hashCode ^ rawUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          protocol == other.protocol &&
          rawUrl == other.rawUrl;
}

class ScannerStats {
  final int totalScanned;
  final int aliveCount;
  final int deadCount;
  final bool isRunning;

  const ScannerStats({
    required this.totalScanned,
    required this.aliveCount,
    required this.deadCount,
    required this.isRunning,
  });

  @override
  int get hashCode =>
      totalScanned.hashCode ^
      aliveCount.hashCode ^
      deadCount.hashCode ^
      isRunning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScannerStats &&
          runtimeType == other.runtimeType &&
          totalScanned == other.totalScanned &&
          aliveCount == other.aliveCount &&
          deadCount == other.deadCount &&
          isRunning == other.isRunning;
}

/// مدل داده دی‌ان‌اس‌های تاییدشده و ضد مسمومیت در مخزن پنهان
class VerifiedDns {
  final String ip;
  final int latencyMs;
  final bool worksSingbox;
  final bool worksTor;
  final bool worksPsiphon;

  const VerifiedDns({
    required this.ip,
    required this.latencyMs,
    required this.worksSingbox,
    required this.worksTor,
    required this.worksPsiphon,
  });

  @override
  int get hashCode =>
      ip.hashCode ^
      latencyMs.hashCode ^
      worksSingbox.hashCode ^
      worksTor.hashCode ^
      worksPsiphon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifiedDns &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          latencyMs == other.latencyMs &&
          worksSingbox == other.worksSingbox &&
          worksTor == other.worksTor &&
          worksPsiphon == other.worksPsiphon;
}
