device_id = "00ded7d5-9daa-4782-8b77-a8c99ff1ad21"
access_token = "55860600-f1f7-4fe2-88ff-beca839d96ef"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8a4d:4443:674c:612:dce6"
wg_private_key = "mPllxHHzk2WYVGoPfEDB+Ldpz0wf1SfiEDrlAswk5X4="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "KqOm"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.9"
