device_id = "551e5a94-dca9-4f38-882f-06e4b96a59ac"
access_token = "839587bf-7687-4f9e-b107-da12841b2a2b"
cert_pem = """
-----BEGIN CERTIFICATE-----
MIHtMIGToAMCAQICAQAwCgYIKoZIzj0EAwIwADAeFw0yNjA5MjgxMTQ4MjRaFw0y
NzA5MjgxMTQ4MjRaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQIAXsQG4hN
msCLen36ZGsVDiZuYTPBPq20mV4+efvx9xGuQpePzfuFgxUkElrRwEdMU8OGgSUO
MwKHCqqTr/KVMAoGCCqGSM49BAMCA0kAMEYCIQCNBuaMMD+gzoAspsLIT+JlZTLR
wSBzH6oedBIaWvA2EQIhAJe2rGgXDu/LuHygsZdLWE3sMSJP5cGwFHM8ePawgm5d
-----END CERTIFICATE-----
"""
key_pem = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgdoEjQJJ1CzgFlgCX
rOoffh7NqNwUyegxpFQz+PBLMtqhRANCAAQIAXsQG4hNmsCLen36ZGsVDiZuYTPB
Pq20mV4+efvx9xGuQpePzfuFgxUkElrRwEdMU8OGgSUOMwKHCqqTr/KV
-----END PRIVATE KEY-----
"""
cert_issued_at = 1790596106
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8c48:5922:4f0c:89f9:4fd8"
wg_private_key = "6JL73AmEHorAfGc8f9U3f/KM0ALLmpx/55sedS7VBXc="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "Nw1s"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.7"
