device_id = "aa1bdd16-f534-4224-aec1-21b1dc2e009d"
access_token = "9719b8d6-dbd1-4be0-9999-62e15daa5e30"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8f87:847c:15e5:fa06:6dae"
wg_private_key = "mNhigL4owqzeTDSLxjTpfdjCtJLCdm9HpMHTStrqzW8="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "j/DI"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
