device_id = "cf383e10-4248-4b76-839f-59888e831c27"
access_token = "2edbbc72-e418-4fb1-b4c8-60cbb7416e3b"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8413:ebc9:6591:e173:f010"
wg_private_key = "iC/poTw7iaacPDyrhhzSKJ63p7CnGT9N3BvpsPOTTEU="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "hcEH"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.5"
