device_id = "c41ca9be-f113-46d3-be13-7cf413730362"
access_token = "f535d3b5-98d4-4f29-8eb5-efcbcb8b3373"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:837e:2f94:dce1:7fe9:5115"
wg_private_key = "IBGcM9zNySyfuRGM6Mv5gFUolzQw1+PUtLOMbFyh7mk="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "/HY7"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.8"
