device_id = "891fa967-dc4b-4499-9ca8-985eb5432051"
access_token = "08c40a5e-d81f-49cc-ac10-b249f7606c6a"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:85cc:60c4:46b2:ef7:fd7b"
wg_private_key = "WCJoF1v/iOVx2WsOKUnZmKmyRrlL9fv2aIaQ/dNuBlo="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "lEJx"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.6"
