device_id = "b825b0d3-94ec-484b-8d2d-df1630712d94"
access_token = "60fb3200-2608-45fb-84d3-79bae43bee9d"
cert_pem = ""
key_pem = ""
cert_issued_at = 0
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:895e:b4cd:a1bf:8520:e372"
wg_private_key = "KIREM/FBqGfcCvn6enADT7mcccChQMdhtoPkotd+bEs="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "g2lR"
organization = ""
gateway_proxy = "172.16.0.1:2480"
assigned_endpoint = "162.159.192.7"
